# Generated by Django 5.0.2 on 2024-02-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecyclePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="recycle_purchase_images/")),
                ("address", models.TextField()),
                ("location_pin", models.CharField(max_length=100)),
                (
                    "types",
                    models.CharField(
                        choices=[
                            ("Bottle", "ขวด"),
                            ("Bag", "ถุง"),
                            ("Crate", "ลัง"),
                            ("Glass bottle", "ขวดแก้ว"),
                            ("Paper", "กระดาษ"),
                            ("Can", "กระป๋อง"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
