# Generated by Django 5.0.2 on 2024-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('bank', models.CharField(max_length=150)),
                ('bank_accounts', models.CharField(max_length=350)),
                ('bank_number', models.CharField(max_length=20)),
                ('pass_bookQR', models.ImageField(upload_to='ImagePassBook/')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
