# Generated by Django 5.0.2 on 2024-02-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
