# Generated by Django 5.0.2 on 2024-02-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0004_garbagetype_recyclepurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='GarbageType',
        ),
        migrations.AlterField(
            model_name='recyclepurchase',
            name='types',
            field=models.ManyToManyField(related_name='recycle_purchases', to='Member.recycletype'),
        ),
    ]
