# Generated by Django 5.0.2 on 2024-02-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0007_garbagetype_recyclepurchase_delete_wastepurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recyclepurchase',
            name='types',
        ),
        migrations.RenameField(
            model_name='recyclepurchase',
            old_name='location_pin',
            new_name='map_pin',
        ),
        migrations.AddField(
            model_name='recyclepurchase',
            name='has_bag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recyclepurchase',
            name='has_bottle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recyclepurchase',
            name='has_can',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recyclepurchase',
            name='has_glass_bottle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recyclepurchase',
            name='has_paper',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recyclepurchase',
            name='image',
            field=models.ImageField(upload_to='recycle_images/'),
        ),
        migrations.DeleteModel(
            name='GarbageType',
        ),
    ]
