# Generated by Django 5.0.2 on 2024-02-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0010_recyclepurchase_created_at_alter_recyclepurchase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclepurchase',
            name='address',
            field=models.TextField(max_length=200),
        ),
    ]
