# Generated by Django 5.0.2 on 2024-02-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0012_recyclepurchase_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclepurchase',
            name='weight_has_bag',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recyclepurchase',
            name='weight_has_bottle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recyclepurchase',
            name='weight_has_can',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recyclepurchase',
            name='weight_has_glass_bottle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recyclepurchase',
            name='weight_has_paper',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
