# Generated by Django 5.0.2 on 2024-02-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Member", "0013_recyclepurchase_weight_has_bag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recyclepurchase",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("กำลังดำเนินการ", "กำลังดำเนินการ"),
                    ("กำลังเข้ารับ", "กำลังเข้ารับ"),
                    ("รับแล้ว", "รับแล้ว"),
                    ("ตรวจสอบขยะ", "ตรวจสอบขยะ"),
                    ("รอชำระเงิน", "รอชำระเงิน"),
                    ("เสร็จสิ้น", "เสร็จสิ้น"),
                    ("ยกเลิก", "ยกเลิก"),
                ],
                default=False,
                max_length=200,
                null=True,
            ),
        ),
    ]
