# Generated by Django 5.0.2 on 2024-02-28 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Member", "0014_alter_recyclepurchase_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recyclepurchase",
            name="has_bag",
        ),
        migrations.RemoveField(
            model_name="recyclepurchase",
            name="weight_has_bag",
        ),
    ]
