# Generated by Django 5.0.2 on 2024-02-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Member", "0016_paymentreceipt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="receipts/")),
            ],
        ),
        migrations.AddField(
            model_name="recyclepurchase",
            name="receipt_image",
            field=models.ImageField(blank=True, null=True, upload_to="receipts/"),
        ),
        migrations.DeleteModel(
            name="PaymentReceipt",
        ),
    ]
