# Generated by Django 5.0.2 on 2024-02-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Member", "0017_receipt_recyclepurchase_receipt_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Receipt",
        ),
        migrations.RemoveField(
            model_name="recyclepurchase",
            name="receipt_image",
        ),
        migrations.AddField(
            model_name="recyclepurchase",
            name="receipt_slip",
            field=models.ImageField(blank=True, null=True, upload_to="receipt_slips/"),
        ),
    ]
