# Generated by Django 5.0.2 on 2024-02-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Member", "0018_delete_receipt_remove_recyclepurchase_receipt_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recyclepurchase",
            name="receipt_slip",
        ),
        migrations.AddField(
            model_name="recyclepurchase",
            name="slip_image",
            field=models.ImageField(blank=True, null=True, upload_to="slip_image/"),
        ),
    ]
