# Generated by Django 5.0.2 on 2024-03-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Member", "0020_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(default="", max_length=20),
        ),
    ]
