# Generated by Django 5.0.2 on 2024-03-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Member", "0021_alter_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
